# -*- coding: utf-8 -*-
"""spotifyDataMining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njC1KZ1Th3xRPZ3dTRKGNh4rIzfh8Y_u
"""

import numpy as np
import pandas as pd
import kagglehub as kh

# Download latest version
path = kh.dataset_download("serkantysz/550k-spotify-songs-audio-lyrics-and-genres")

print("Path to dataset files:", path)

import os
import pandas as pd

path = '/root/.cache/kagglehub/datasets/serkantysz/550k-spotify-songs-audio-lyrics-and-genres/versions/1'
# Load both datasets directly
dfA = pd.read_csv(os.path.join(path, 'artists.csv'))
dfS = pd.read_csv(os.path.join(path, 'songs.csv'))

print("Artists Data:")
display(dfA.head())
print("\nSongs Data:")
display(dfS.head())

"""# What are we looking for?

1. Predict song genre/sub-genre from audio features

2. predict popularity from audio + artist metrics + lyrics


3. how to make a "hit song" based off of features


4. content based recommendation system

✦ Supervised Learning (Labeled Data)
  In Supervised Learning, the model learns from input-output pairs. You provide the "answer key" during training.


  1. Regression (Continuous Outputs)
   * Popularity Forecasting: Predict the exact popularity score (0-100) based on energy, tempo, and loudness.
   * Release Year Estimation: Predict the year a song was released based on its "sonic signature" (e.g., 80s gated
     reverb vs. modern compression).
   * Streaming Count Prediction: Estimating total plays based on artist followers and initial 24-hour performance.


  2. Classification (Discrete Categories)
   * Genre Labeling: Predict if a song belongs to Rock, Pop, or Hip-Hop using audio features.
   * Explicit Content Filter: A binary classifier (0 or 1) that analyzes lyrics to determine if a song should be
     marked "Explicit."
   * Mood Classification: Categorizing songs into "Happy," "Sad," "Angry," or "Chill" based on valence and energy
     levels.
   * Hit/Flop Prediction: A binary classifier that predicts if a song will reach the Top 50 based on early metrics.

  ---


  Unsupervised Learning (Unlabeled Data)
  In Unsupervised Learning, the model identifies hidden patterns or structures in the data without being told what
  the "correct" output is.


  1. Clustering (Grouping)
   * Micro-Genre Discovery: Using K-Means to group songs into 50+ hyper-specific clusters (e.g., "Dark Lo-fi
     Hip-Hop") that don't exist in the standard genre column.
   * Artist Segmenting: Grouping artists based on their followers vs. popularity to identify "Underground Gems,"
     "Rising Stars," and "Mainstream Giants."
   * User Persona Mapping: Clustering users based on their listening history to define distinct "Listener Profiles"
     (e.g., "The Gym Motivator," "The Deep Work Coder").


  2. Association Rules (Relationships)
   * Market Basket Analysis: If a user likes Artist A, they have an 85% probability of liking Artist B. This is the
     foundation of "Fans also like" sections.
   * Sequential Pattern Mining: Identifying that users who listen to Lo-fi Beats in the morning often switch to
     Synthwave in the evening.


  3. Dimensionality Reduction (Simplification)
   * Visualization: Using PCA (Principal Component Analysis) or t-SNE to squash 20+ audio features into a 2D or 3D
     map. This allows you to "see" the distance between musical styles.
   * Noise Reduction: Removing redundant features that are highly correlated (like loudness and energy) to make
     models faster and more accurate.


  4. Anomaly Detection (Outlier Detection)
   * Identifying Non-Music: Automatically flagging white noise tracks, podcasts, or "joke" songs that deviate
     significantly from standard musical structures.
   * Bot Detection: Identifying artificial streaming patterns that don't match human listening behavior.


  For your project: You are combining Supervised Regression (Popularity) with Unsupervised Clustering
  (Hyper-specific playlists). This "Hybrid Approach" is exactly how modern recommendation engines like Spotify's
  Discover Weekly actually function.
"""

missing = dfS.isnull().sum()
percent_missing = (missing / len(dfS)) * 100
report = pd.DataFrame({'Missing Count:' missing, 'Percent Missing': percent_missing})