# -*- coding: utf-8 -*-
"""spotifyDataMining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njC1KZ1Th3xRPZ3dTRKGNh4rIzfh8Y_u
"""

import numpy as np
import pandas as pd
import kagglehub as kh

# Download latest version
path = kh.dataset_download("serkantysz/550k-spotify-songs-audio-lyrics-and-genres")

print("Path to dataset files:", path)

import os
import pandas as pd

path = '/root/.cache/kagglehub/datasets/serkantysz/550k-spotify-songs-audio-lyrics-and-genres/versions/1'
# Load both datasets directly
dfA = pd.read_csv(os.path.join(path, 'artists.csv'))
dfS = pd.read_csv(os.path.join(path, 'songs.csv'))

print("Artists Data:")
display(dfA.head())
print("\nSongs Data:")
display(dfS.head())


missing = dfS.isnull().sum()
percent_missing = (missing / len(dfS)) * 100
report = pd.DataFrame({'Missing Count:' missing, 'Percent Missing': percent_missing})
